# Generated by Django 5.2.11 on 2026-02-23 23:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='available_seats',
        ),
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journey_date', models.DateField()),
                ('available_seats', models.IntegerField(blank=True, null=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
            ],
            options={
                'unique_together': {('train', 'journey_date')},
            },
        ),
    ]
